server:
  port: 8083
spring:
  application:
    name: service-employee
  config:
    import: "optional:configserver:http://localhost:8088/config/"
  boot:
    admin:
      client:
        url: "http://localhost:8085/sb-admin"
#  zipkin:
#    base-url: "http://localhost:9411/"
#    service:
#      name: service-employee
#
#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
